#include "TestHarness.h" 

TEST (CHECK_STRINGS_EQUAL,MyTest1)
{
    CHECK_STRINGS_EQUAL("USA","USA","USA==USA");
}	
TEST (CHECK_STRINGS_EQUAL,MyTest2)
{
    CHECK_STRINGS_EQUAL("US","USA","US==USA");
}	

TEST (CHECK_STRINGS_EQUAL,MyTest3)
{
    CHECK_STRINGS_EQUAL("JP","USA","JP==USA");
}	
